In [1]:
import numpy as np

In [2]:
arr=np.array([12,23,34,56])
print(arr)

[12 23 34 56]


In [4]:
# Insert element in array
print(np.append(arr,45))
print(np.append(arr,[334,55]))

[12 23 34 56 45]
[ 12  23  34  56 334  55]


In [5]:
# Insert element at index wise
print(np.insert(arr,2,2))

[12 23  2 34 56]


In [6]:
arr1 = ([10,20,30],[30,54,56])
print(arr1)

([10, 20, 30], [30, 54, 56])


In [11]:
# Delete element in array
print(np.delete(arr,2))

[12 23 56]


In [8]:
#insert element in 2D array
print(np.append(arr1,56))

[10 20 30 30 54 56 56]


In [14]:
print(np.insert(arr1,1,[23,32], axis=1))

[[10 23 20 30]
 [30 32 54 56]]


In [17]:
print(np.delete(arr1,1, axis=0))

[[10 20 30]]
