In [33]:
import numpy as np
import statistics as s

In [34]:
arr = np.array([10,3,21,34,56,90])
print(arr)

[10  3 21 34 56 90]


In [35]:
# Aggregating functions in array
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.size(arr))

214
3
90
6


In [36]:
print(np.mean(arr))
print(np.cumsum(arr)) #cumilative sum
print(np.cumprod(arr)) #cumilative product

35.666666666666664
[ 10  13  34  68 124 214]
[       10        30       630     21420   1199520 107956800]


In [37]:
a=[100,150,199,200,250,130]
b=[10,50,30,40,30,10]
price = np.array(a)
quantity = np.array(b)
print(price,"\n",quantity)



[100 150 199 200 250 130] 
 [10 50 30 40 30 10]


In [40]:
# basic statistical function
print(np.mean(arr))
print(np.median(arr))
print(s.mode(arr))
print(np.std(arr))
print(np.var(arr))

35.666666666666664
27.5
10
29.747082023097473
884.8888888888888


In [45]:
#Cofficient of corelation
# -1 represent inversely proportional relationship
# +1 represent proportional relationhip
# 0 means no relationship
d1=np.array([12,23,34,43,1])
d2=np.array([21,78,21,34,45])
print(np.corrcoef([d1,d2]))

[[ 1.         -0.14555496]
 [-0.14555496  1.        ]]
