In [5]:
import numpy as np

In [6]:
# Creating an array using Numpy
arr = np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [7]:
# 2-D array
arr = np.array([[10,20,30],[20,40,60]])
print(arr)
print(type(arr))

[[10 20 30]
 [20 40 60]]
<class 'numpy.ndarray'>


In [8]:
# Slicing in array
#index         0  1  2  3  4  5  6  7
arr=np.array([10,20,30,40,50,60,70,80])
#index      -8  -7  -6  -5  -4  -3  -2 -1
print(arr[0:]) # print the whole array
print(arr[0:5]) # print the array of index 4
print(arr[3:5]) # print the array from 3rd index to 4th index
print(arr[2:6]) #print the array from 2nd index to 5th index
print(arr[3:]) #print the array from 3rd index to n-1 index
print(arr[-4:-1]) #print -4th index to -2nd index
print(arr[::-1]) #print the reverse of array

[10 20 30 40 50 60 70 80]
[10 20 30 40 50]
[40 50]
[30 40 50 60]
[40 50 60 70 80]
[50 60 70]
[80 70 60 50 40 30 20 10]


In [9]:
# Slicing on 2D array
arr = np.array([[10,20,30],[20,40,60]])
#print(arr[0:2,0:2])
#print(arr[0:2, 0:3])
print(arr[0,1:3])


[20 30]


In [10]:
# Array Attributes
arr=np.array([10,20,30,40])
arr1 = np.array([[10,20,30],[20,40,60]])
print(np.shape(arr)) # return the no. of rows and cols 
print(np.shape(arr1)) # return the no. of rows and cols in 2D array
print()
# Return the size of array
print(np.size(arr))
print(np.size(arr1)) 
print()
# Return the dimension of array
print(np.ndim(arr))
print(np.ndim(arr1))

(4,)
(2, 3)

4
6

1
2


In [14]:
#some other attributes of array
arr=np.array([10,20,30,40])
arr1 = np.array([[10,20,30],[20,40,60]])
print(len(arr))
print(len(arr1))
print()
print(arr.dtype)
print(arr1.dtype)

4
2

int32
int32


In [24]:
#convert the array to different types
arr=np.array([10,20,30,40])
print(arr.astype(str))
print(arr.dtype)

['10' '20' '30' '40']
int32
