In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
arr2=np.add(arr,arr1)
print(arr,arr1,arr2)

[1 2 3] [4 5 6] [5 7 9]


In [4]:
# concate arr and arr2
print(np.concatenate([arr,arr2]))

[1 2 3 5 7 9]


In [5]:
# concate axis wise
# vetically concate
#print(np.concatenate([arr,arr2], axis=0))
#or
print(np.vstack([arr3,arr4])) #  it also use to concate vertically

[1 2 3 5 7 9]


In [8]:
# horizontally concate - 2D array need
arr3=np.array([[1,2,3],[4,5,6]])
arr4=np.array([[5,7,8],[8,9,10]])
#print(np.concatenate([arr3,arr4], axis=1))
#or
print(np.hstack([arr3,arr4])) # it also use to concate horizontally

[[ 1  2  3  5  7  8]
 [ 4  5  6  8  9 10]]


In [13]:
# Split the array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
di = np.split(arr,5) #5 means the split function split the array in 5 different array and you can change the value according to you
print(di)
print(di[1])

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[3 4]
