In [1]:
import numpy as np

In [3]:
arr=np.array([10,20,34,40])
arr1=np.array([5,18,40,35])
print(arr,arr1)

[10 20 34 40] [ 5 18 40 35]


In [17]:
# Mathematical operation
print(np.add(arr,arr1))
print(np.subtract(arr,arr1))
print(np.multiply(arr,arr1))
print(np.divide(arr,arr1))

[15 38 74 75]
[ 5  2 -6  5]
[  50  360 1360 1400]
[2.         1.11111111 0.85       1.14285714]
[100000      0      0      0]


In [20]:

arr = np.array([[1,2,3],[4,5,6]])
arr1=np.array([[4,5,9],[9,8,7]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
# 2D arrays mathematical operation:
print(np.add(arr,arr1))
print(np.subtract(arr,arr1))
print(np.multiply(arr,arr1))
print(np.divide(arr,arr1))

[[ 5  7 12]
 [13 13 13]]
[[-3 -3 -6]
 [-5 -3 -1]]
[[ 4 10 27]
 [36 40 42]]
[[0.25       0.4        0.33333333]
 [0.44444444 0.625      0.85714286]]
