In [1]:
import numpy as np

In [7]:
arr = np.array([78,12,34,100,200,123,1])
arr1 = np.array([[12,54,65,1,2],[90,89,100,200,43]])
print(arr)
print()
print(arr1)

[ 78  12  34 100 200 123   1]

[[ 12  54  65   1   2]
 [ 90  89 100 200  43]]


In [8]:
#Sort the 1D array and 2D array
print(np.sort(arr))
print()
print(np.sort(arr1))

[  1  12  34  78 100 123 200]

[[  1   2  12  54  65]
 [ 43  89  90 100 200]]


In [14]:
# Search element in array
s = np.where(arr == 100)
s1= np.where(arr %2 == 0)
s2=np.where(arr1 == 89)
print(s)
print()
print(s1)
print()
print(s2)

(array([3], dtype=int64),)

(array([0, 1, 2, 3, 4], dtype=int64),)

(array([1], dtype=int64), array([1], dtype=int64))


In [15]:
arr = np.array([1,2,3,4,5,6]) # array must be sorted for searchsorted
ss = np.searchsorted(arr,5)
print(ss)

4


In [16]:
# Filter in array
fa = [False,True,False,True,False,False]
new_arr = arr[fa]
print(new_arr)

[2 4]


In [17]:
fa = arr>2
new_arr = arr[fa]
print(new_arr)

[3 4 5 6]
